### ISSUE TITLE
Optimization considerations and refactor code

### ISSUE THREAD

**Issue by kenanmasri** [kenanmasri/3lm#3]
### To-do:
- [ ] Remove LexStack class, it is unnecessary.
- [ ] Find ways to improve the lexer, parser, and interpreter codes.
- [ ] Write additional plugins.
